stages:
  - build
  - test
  - release
  - silly

build:
  stage: build
  only:
    changes:
      - APKBUILD
  image: registry.gitlab.com/daverona/docker/apkbuild:3.10
  artifacts:
    when: on_success
    expire_in: 60 min
    paths:
      - APKINDEX.tar.gz
      - ./*.apk
  script:
    # Prepare inputs
    - echo "$ABUILD_PRIVKEY" > "/abuild/.abuild/$ABUILD_KEYNAME.rsa"
    - echo "$ABUILD_PUBKEY" | sudo tee "/etc/apk/keys/$ABUILD_KEYNAME.rsa.pub"
    - export PACKAGER_PRIVKEY="/abuild/.abuild/$ABUILD_KEYNAME.rsa"
    # Build APKs
    - abuild-apk update
    - cp -R APKBUILD /work
    - cd /work && abuild -r -c && cd -
    # Prepare outputs 
    - export APKBUILD_ARCH=$(arch)
    - cp /packages/$APKBUILD_ARCH/* .

test:
  stage: test
  dependencies:
    - build
  only:
    changes:
      - APKBUILD
  image: alpine:3.10
  script:
    # Test installing APKs
    - echo "$BUILDER_PUBKEY" > "/etc/apk/keys/$BUILDER_KEYNAME.rsa.pub"
    - apk add -v *.apk
    # Test executable

release:
  stage: release 
  dependencies:
    - build
  only:
    refs:
      - tags
    changes:
      - APKBUILD
  script:
    # Think how to get artifacts and release them.
    - echo "You silly."

silly:
  stage: silly
  script:
    - echo "You silly."
